/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as implementationSol from "./Implementation.sol";
export type { implementationSol };
export type { MyTransparentProxy } from "./MyTransparentProxy";
export type { TranslucentUpgradeableProxyV2 } from "./TranslucentUpgradeableProxyV2";
