/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ImplementationV2,
  ImplementationV2Interface,
} from "../../../contracts/Implementation.sol/ImplementationV2";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int256",
        name: "newValue",
        type: "int256",
      },
    ],
    name: "TotalValueChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_num1",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_num2",
        type: "int256",
      },
    ],
    name: "multiply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_num1",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_num2",
        type: "int256",
      },
    ],
    name: "sum",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalValue",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102168061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633c4308a8146100465780639967062d1461005b578063d4c3eea01461006e575b600080fd5b61005961005436600461014a565b610088565b005b61005961006936600461014a565b6100d8565b6100766100e5565b60405190815260200160405180910390f35b61009a6100958284610182565b6100f4565b7fb2c7e32a7456258260ed4df8e5b860d6198099383c94b274021bfd9a6f7ac87a6100c3610120565b60405190815260200160405180910390a15050565b61009a61009582846101b8565b60006100ef610120565b905090565b61011d7f7143077388da7263f151574bb8b431587ba155ce26e1a98a058a9a5b7c458d3b829055565b50565b60006100ef7f7143077388da7263f151574bb8b431587ba155ce26e1a98a058a9a5b7c458d3b5490565b6000806040838503121561015d57600080fd5b50508035926020909101359150565b634e487b7160e01b600052601160045260246000fd5b80820260008212600160ff1b8414161561019e5761019e61016c565b81810583148215176101b2576101b261016c565b92915050565b80820182811260008312801582168215821617156101d8576101d861016c565b50509291505056fea2646970667358221220755a09d408a8ce8274cbada6e89ac5c7c7801708246553321cc77f86003256d664736f6c634300081c0033";

type ImplementationV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationV2__factory extends ContractFactory {
  constructor(...args: ImplementationV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImplementationV2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ImplementationV2__factory {
    return super.connect(runner) as ImplementationV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationV2Interface {
    return new Interface(_abi) as ImplementationV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ImplementationV2 {
    return new Contract(address, _abi, runner) as unknown as ImplementationV2;
  }
}
