/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ImplementationV1,
  ImplementationV1Interface,
} from "../../../contracts/Implementation.sol/ImplementationV1";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int256",
        name: "newValue",
        type: "int256",
      },
    ],
    name: "TotalValueChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_num1",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_num2",
        type: "int256",
      },
    ],
    name: "sum",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalValue",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102978061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639967062d1461003b578063d4c3eea014610057575b600080fd5b61005560048036038101906100509190610184565b610075565b005b61005f6100cb565b60405161006c91906101d3565b60405180910390f35b6100898183610084919061021d565b6100da565b7fb2c7e32a7456258260ed4df8e5b860d6198099383c94b274021bfd9a6f7ac87a6100b2610107565b6040516100bf91906101d3565b60405180910390a15050565b60006100d5610107565b905090565b6101047f7143077388da7263f151574bb8b431587ba155ce26e1a98a058a9a5b7c458d3b82610137565b50565b60006101327f7143077388da7263f151574bb8b431587ba155ce26e1a98a058a9a5b7c458d3b61013e565b905090565b8082555050565b600081549050919050565b600080fd5b6000819050919050565b6101618161014e565b811461016c57600080fd5b50565b60008135905061017e81610158565b92915050565b6000806040838503121561019b5761019a610149565b5b60006101a98582860161016f565b92505060206101ba8582860161016f565b9150509250929050565b6101cd8161014e565b82525050565b60006020820190506101e860008301846101c4565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006102288261014e565b91506102338361014e565b92508282019050828112156000831216838212600084121516171561025b5761025a6101ee565b5b9291505056fea26469706673582212208656ad6863e75702fdf5bbb40c8423702227002ec433e26749603bff4857eac964736f6c634300081c0033";

type ImplementationV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationV1__factory extends ContractFactory {
  constructor(...args: ImplementationV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImplementationV1 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ImplementationV1__factory {
    return super.connect(runner) as ImplementationV1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationV1Interface {
    return new Interface(_abi) as ImplementationV1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ImplementationV1 {
    return new Contract(address, _abi, runner) as unknown as ImplementationV1;
  }
}
